### ISSUE TITLE
Yale or Sidney Lau

### ISSUE THREAD

**Issue by LawranceFung** [jyutnet/cantonese-books-data#27]
Do you have any dictionaries with Sidney Lau or Yale romanization?

**Comment by jyutnet** [comment]
I don't have any dictionary that adopts the romanization schemes you mentioned on hand.

I only know one work that uses Sidney Lau romanization. That is 國音粵音索音字彙 by 張勵妍/張賽洋, published 1987.

And for Yale romanization, I'm yet to find any (Chinese) dictionary that adopts such a scheme. I think it is more used by Cantonese textbooks/dictionaries targeted for non-native speakers, like [this](https://www.amazon.com/English-Cantonese-Dictionary-Cantonese-Yale-Romanization/dp/9622019706), and [this](https://www.amazon.com/Periplus-Pocket-Cantonese-Dictionary-Cantonese-English/dp/0794607802/ref=pd_sbs_1/147-7040598-8662929?pd_rd_w=Q41Ne&pf_rd_p=3676f086-9496-4fd7-8490-77cf7f43f846&pf_rd_r=N4AMH6ZJSQWTCS7W3SNC&pd_rd_r=694b2c3c-258a-4c79-8d46-49e11c5e0aba&pd_rd_wg=Aw2sP&pd_rd_i=0794607802&psc=1).

**Comment by LawranceFung** [comment]
Any chance of including those dictionaries?  It's more data and could be useful for some.  For example, Sidney Lau preserves glides in characters like gwoo1=菇, and Yale is more likely to select English loanwords that might get passed over in other schemes.  Yale and Sidney Lau also both distinguish the high falling from the high level tone.  I think a more diverse selection of dictionary data yields a more robust overall corpus - Cantonese is widely spoken but uncommonly written and preserved, and in my work I try to go above and beyond in including more slang and quirks of it.  
I know 實用粵英詞典 also uses Sidney Lau

**Comment by jyutnet** [comment]
I didn't mention 實用粵英詞典 because Sidney Lau is the author of this book, so it seems obvious enough that the book uses his own romanization system. I don't have a copy of 實用粵英詞典, but this and 國音粵音索音字彙 will not be considered for inclusion of this project for this moment because they are still purchasable.

Please also note that this project does *not* guarantee the preservation of the original romanization scheme for the digitized data. Unless the material being digitized does not reflect the modern Cantonese phonetic system, they will all be converted to Jyutping. I'd recommend users to consult the source materials for the original transcription system.

As for the transcription advantages(?) of S. L./Yale system you've mentioned, I believe no Cantonese romanization scheme precludes the existence of the labialized form of [k]/[kʰ] before [u:] by itself. Whether to use labialized form ([kw]/[kwʰ]) to denote the onset of 菇 ([u:]) is up to the decision or interpretation of the editors. For instance, while 國音粵音索音字彙 uses the S. L. system, 菇 is transcripted as "goo1", not "gwoo1". On the contrary, there are [several materials use [gwu:] to denote the pronunciation of 菇](https://jyut.net/query?q=%E8%8F%87), and they are well preserved in the digitized version using Jyutping. While on it, 國音粵音索音字彙 also does not differentiate high falling from the high level tone.

**Comment by LawranceFung** [comment]
I don't mind purchasing them - I actually have a copy of 實用粵英詞典, but digitizing all the data is a long chore. I can confirm it transcribes 菇 as gwoo1.  I am not sure if the Sidney Lau system preceded that change in pronunciation, but he certainly documented it.  The dictionary also distinguishes high falling and high level tones - frankly, that's of most interest to me, since compared to glides or sibilants, it's kind of a uniquely Cantonese phenomenon.

**Comment by jyutnet** [comment]
In this case using first hand materials would be the best. Closing as there's no actionable item.

**Comment by LawranceFung** [comment]
is Sidney Lau and Yale without loss of glides and tones against the philosophy of the project, or simply not supported at this time?

**Comment by jyutnet** [comment]
Honestly I'm not quite sure what your "Sidney Lau and Yale without loss of glides and tones" refers to, but let me try to clarify my points here. It is me, the maintainer, who decides which material shall be included in this repository. It depends on a number of factors, but the original transcription system of the book isn't one of them. If what you want is a digitized version of 實用粵英詞典, I have already answered why it is not considered for inclusion at this moment. I also explained that even if it is digitized, the result may still not be what you want, because preseving the books' original form of transcription is not of paramount importance - this project aims to provide pronunciation references for modern practical use, and there is no guarantee if this will happen.

**Comment by LawranceFung** [comment]
If all dictionary data that goes in is transcribed in Jyutping then when extrapolating back to Sidney Lau gwoo1=菇 and Yale tìm=添, the w and ` are lost.  
Are historical nuances in pronunciation "not considered for inclusion at this moment" or never will be?  I am fine if it is against the scope of the project but it is nice to know.

**Comment by jyutnet** [comment]
Firstly, as for this "gwoo1=菇" concern, I have already explained this has nothing to do with the transcription system itself with a proof from [jyut.net](https://jyut.net/query?q=%E8%8F%87) which uses Jyutping as shows pronunciations in Jyutping. I'd also answered a similar question [here](https://github.com/jyutnet/cantonese-books-data/issues/9#issuecomment-583958399), with a quote from LSHK. In short, assuming Jyuping would "lose" the gw ([kʷ]) onset for words like 菇 is basically unfounded:

| Jyutping | Sidney Lau's equivalent |
| --------- | ------------------------ |
| gwu1     |  gwoo1  |
| gu1        |  goo1  |

The above two groups can be losslessly converted between each other. This probably applies to most if not all of the modern Cantonese transcriptions systems. 

Secondly, it is true that Jyutping doesn't distinguish between high flat and high falling tones:
![jp](https://user-images.githubusercontent.com/7262459/150620797-9a758873-fc23-471a-a939-efbc261476ae.jpg)
*Source: 香港語言學學會《粵語拼音方案》的緣起、設計原則和特點*
 
So, converting a pronunciation from Sidney Lau to Jyutping may result in loss of information. But whether this is really the case depends not only the transcription system itself, but also how the author of the book make of it, because adopting one's transcription system doesn't imply adopting one's transcription for all words. Which is why it's completely fine for 張勵研's 國音粵音索音字彙 to mark 金 as "gam1", despite Lau's book is marking 金 as "gam1̊ ".

Lastly, it is the **book** 實用粵英詞典 itself that is deemed not suitable (yet) for inclusion right now, not the original transcription system nor the *historical nuances in pronunciation* as you've mentioned.

**Comment by LawranceFung** [comment]
Thank you for clarifying.  I find it easy to transcribe the high falling tone as '7'
